[application]

name = "synthcat"
out_dir = "dist"

[web.app]

# HTML title tag content
title = "synthcat"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
publisher = "ColetivoATS"
identifier = "com.synthcat"